let bookList = [
    {
        id: "the-alchemist",
        title: "The Alchemist",
        author: "Paulo Coelho",
        genre: "fiction",
        mood: "inspiring",
        description: "A young shepherd named Santiago sets out on a journey to find treasure, but along the way, he discovers the true meaning of life, dreams, and following one’s heart. A simple yet powerful story about destiny and self-discovery.",
        rating: 4.7,
        image: "assets/images/Alchemist.jpg",
        link: "https://www.amazon.in/Alchemist-25th-Anniversary-Paulo-Coelho/dp/0062390627"
    },
    {
        id: "harry-potter",
        title: "Harry Potter",
        author: "J.K. Rowling",
        genre: "fantasy",
        mood: "adventure",
        description: "A young boy discovers he is a wizard and begins an extraordinary journey at a magical school. Along the way, he faces challenges, builds strong friendships, and learns about courage, love, and destiny.",
        rating:4.8,
        image: "assets/images/Harry Potter.jpg",
        link: "https://www.amazon.in/Harry-Potter-Box-Set-Collection/dp/B09MMKZQ85",
        popular: true
    },
    {
        id: "pride-and-prejudice",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "romance",
        mood: "happy",
        description:" A timeless story of love, misunderstandings, and personal growth. It follows Elizabeth Bennet as she navigates society, family expectations, and her evolving feelings toward the reserved Mr. Darcy.",
        rating: 4.6,
        image: "assets/images/Pride and Prejudice.png",
        link: "https://www.amazon.in/Pride-Prejudice-Original-publication-January-ebook/dp/B07MFTF9B4",
      
    },
    {
        id: "the-silent-patient",
        title: "The Silent Patient",
        genre: "thriller",
        mood: "sad",
        description: "A psychological thriller about a woman who stops speaking after committing a shocking crime. As a therapist tries to uncover her story, hidden truths and unexpected twists begin to unfold.",
        rating: 4.5,
        image: "assets/images/The Silent Patient.jpg",
        link: "https://www.amazon.in/Silent-Patient-Alex-Michaelides/dp/125030170X"
    },
    { 
        id: "atomic-habits",    
        title: "Atomic Habits",
        author: "James Clear",
        genre:"selfhelp",
        mood: "inspiring",
        description:"A practical guide that teaches how small daily habits can lead to remarkable personal growth and success over time.",
        rating: 4.8,
        image: "assets/images/Atomic Habits.jpg",
        link: "https://www.amazon.in/Atomic-Habits-James-Clear/dp/1847941834"

    },
    {
        title: "The Summer I Turned Pretty",
        author: "Jenny Han",
        genre: "romance",
        mood: "happy",
        description: "A coming-of-age story about love, friendship, and growing up during unforgettable summers by the beach.",
        rating: 4.3,
    image:"assets/images/The Summer I Turned Pretty.jpg",
    link:"https://www.amazon.in/Summer-Turned-Pretty-Trilogy-Boxed/dp/1665973730?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1WYWER0W24N8S",
    popular: true
},

{
    id: "to-all-the-boys-ive-loved-before",
    title: "To All the Boys Ive Loved Before",
    author: "Jenny Han",
    genre: "romance",
    mood: "happy",
    description: "A sweet and relatable story about a girl whose secret love letters are accidentally sent out, changing her life completely.",
    rating: 4.4,
    image:"assets/images/To All the Boys Ive Loved Before.jpg",
    link:"https://www.amazon.in/All-Boys-Ive-Loved-Before/dp/1407149075",
    
},

{
    id: "the-palace-of-illusions",
    title: "The Palace of Illusions",
    author: "Chitra Banerjee Divakaruni",
    genre: "fiction",
    mood: "thoughtful",
    description: "A retelling of the Mahabharata from Draupadi’s perspective, exploring her emotions, struggles, and strength.",
    rating: 4.5,
    image:"assets/images/The Palace of Illusions.jpg",
    link:"https://www.amazon.in/Palace-Illusions-Chitra-Divakaruni-ebook/dp/B004E9T0KY",
    popular: true
    
},

{
    id: "once-upon-a-curfew",
    title: "Once Upon a Curfew",
    author: "Srishti Chaudhary",
    genre: "fiction",
    mood: "nostalgic",
    description: "A story set in conflict-torn Kashmir that portrays the emotional and social struggles of people living under constant tension.",
    rating: 4.2,
    image:"assets/images/Once Upon a Curfew.jpg",
    link:"https://www.amazon.in/Once-Upon-Curfew-Srishti-Chaudhary-ebook/dp/B07QKL6KF5",
   
},

{
    id: "it-ends-with-us",
    title: "It Ends With Us",
    author: "Colleen Hoover",
    genre: "romance",
    mood: "emotional",
    description: "A powerful story about love, relationships, and difficult choices, dealing with sensitive themes like domestic abuse.",
    rating: 4.7,
    image:"assets/images/It Ends With Us.jpg",
    link:"https://www.amazon.in/Colleen-Hoover-Ends-Boxed-Set/dp/1668021064?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1WYWER0W24N8S",
    popular: true
},

{
    id: "the-seven-husbands-of-evelyn-hugo",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "fiction",
    mood: "emotional",
    description: "A glamorous and emotional story about a reclusive Hollywood icon revealing her life, secrets, and seven marriages.",
    rating: 4.6,
    image:"assets/images/The Seven Husbands of Evelyn Hugo.jpg",
    link:"https://www.amazon.in/Seven-Husbands-Evelyn-Hugo-Novel/dp/1501139231",
},

{
    id: "verity",
    title: "Verity",
    author: "Colleen Hoover",
    genre: "thriller",
    mood: "dark",
    description: "A gripping psychological thriller about a struggling writer who uncovers disturbing truths while completing another author's manuscript.",
    rating: 4.5,
    image:"assets/images/Verity.jpg",
    link:"https://www.amazon.in/Psychological-Thriller-Romantic-Suspense-Paperback/dp/B0GTQH4BBG?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AZ3CVHCPNOSID",   
},
{
    id: "why-bharat-matters",
    title: "Why Bharat Matters",
    author: "S. Jaishankar",
    genre: "nonfiction",
    mood: "thoughtful",
    description:"This book explains India’s growing role in global politics and why it matters in today’s world. It gives insights into foreign policy, national interests, and how India is shaping international relations in a changing global scenario.",
    rating: 4.6,
    image:"assets/images/Why Bharat Matters.jpg",
    link:"https://www.amazon.in/Why-Bharat-Matters-S-Jaishankar/dp/9354223807",

},
{
    id: "calling-sehmat",
    title: "Calling Sehmat",
    author: "Harinder Sikka",
    genre: "fiction",
    mood: "patriotic",
    description:"This book explains India’s growing role in global politics and why it matters in today’s world. It gives insights into foreign policy, national interests, and how India is shaping international relations in a changing global scenario.",
    rating: 4.5,
    image:"assets/images/Calling Sehmat.jpg",
    link:"https://www.amazon.in/Calling-Sehmat-Harinder-Sikka-ebook/dp/B07CVL29ZC",
},
{
    id: "malgudi-days",
    title: "Malgudi Days",
    author: "R.K. Narayan",
    genre: "fiction",
    mood: "nostalgic",
    description:"A collection of short stories set in the fictional town of Malgudi, capturing simple everyday moments of life. The stories bring a sense of nostalgia, innocence, and warmth through relatable characters and situations.",
    rating: 4.7,
    image:"assets/images/Malgudi Days.jpg",
    link:"https://www.amazon.in/-/hi/R-K-Narayan/dp/0143039652",
},
{
    id: "grandmas-bag-of-stories",
    title: "Grandma's Bag of Stories",
    author: "Sudha Murty",
    genre: "fiction",
    mood: "happy",
    description: "A delightful collection of short stories filled with wisdom, values, and warmth, perfect for all ages.",
    rating: 4.6,
    image: "assets/images/Grandma's Bag of Stories.jpg",
    link: "https://www.amazon.in/GRANDMAS-BAG-STORIES-SUDHYA-MURTY/dp/B0DS2F8Z5K",
   
},
{
    id: "the-blue-umbrella",
    title: "The Blue Umbrella",
    author: "Ruskin Bond",
    genre: "fiction",
    mood: "happy",
    description: "A simple yet heartwarming story of a young girl and her prized blue umbrella, highlighting kindness and human emotions.",
    rating: 4.5,
    image: "assets/images/The Blue Umbrella.jpg",
    link: "https://www.amazon.in/Blue-Umbrella-Ruskin-Bond/dp/8129124548?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1WYWER0W24NS",
    popular: true
},
{
    id: "train-to-pakistan",
    title: "Train to Pakistan",
    author: "Khushwant Singh",
    genre: "fiction",
    mood: "emotional",
    description: "A powerful novel set during the partition of India, showing the human cost of violence and the strength of love.",
    rating: 4.6,
    image: "assets/images/Train to Pakistan.jpg",
    link: "https://www.amazon.in/Train-Pakistan-Khushwant-Singh/dp/0143065882?s=bazaar",
    popular: true
},
{
    id: "rich-dad-poor-dad",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    genre: "nonfiction",
    mood: "inspiring",
    description: "A personal finance book that teaches the difference between working for money and making money work for you.",
    rating: 4.6,
    image: "assets/images/Rich Dad Poor Dad.jpg",
    link: "https://www.amazon.in/Rich-Dad-Poor-Anniversary-Middle/dp/B07QRWSKG6"
},
{
    id: "ikigai",
    title: "Ikigai",
    author: "Héctor García",
    genre: "nonfiction",
    mood: "inspiring",
    description: "A Japanese concept that helps you discover your purpose in life by balancing passion, mission, vocation, and profession.",
    rating: 4.6,
    image: "assets/images/Ikigai.jpg",
    link: "https://www.amazon.in/Ikigai-Japanese-secret-long-happy-ebook/dp/B073D36KNM",
    popular: true
},
{
    id: "wings-of-fire",
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    genre: "nonfiction",
    mood: "inspiring",
    description: "An autobiography of India’s missile man, sharing his journey, struggles, and vision for the nation.",
    rating: 4.8,
    image: "assets/images/Wings of Fire.jpg",
    link: "https://www.amazon.in/Wings-Fire-Abdul-Kalam-Autobiography/dp/B0FTSLB7Z4/ref=asc_df_B0FTSLB7Z4?mcid=2f937f998a863bb3b72d6fa839f7f4b6&tag=googleshopdes-21&linkCode=df0&hvadid=710047294719&hvpos=&hvnetw=g&hvrand=1182371609524396406&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9304071&hvtargid=pla-2448355407506&psc=1&hvocijid=1182371609524396406-B0FTSLB7Z4-&hvexpln=0&gad_source=1",
    popular: true
},
];